from typing import Protocol
import numpy as np
from src.activation.activation import Array


class Model(Protocol):
    """Cualquier cosa que implemente esta interfaz puede entrenarse con Trainer."""

    def forward(self, x: Array) -> Array: ...
    def backward(self, grad_output: Array) -> None: ...
    def get_weights(self) -> list[tuple[Array, Array]]: ...
    def get_grads(self) -> list[tuple[Array, Array]]: ...
    def set_weights(self, weights: list[tuple[Array, Array]]) -> None: ...